swagger: '2.0'
info:
  description: OpenAPI document for System for tracking children at school
  version: '1.0'
  title: System for tracking REST API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8080
basePath: "/"
tags:
 - name: "user"

paths:
  "/signup":
    post:
      tags:
        - user
      summary: Create a new user
      operationId: createUserUsingPOST
      consumes:
        - application/json
      produces:
        - "*/*"
      parameters:
        - in: body
          name: user
          description: User object stores in the database
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/User"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    "/{id}"
    get:
      tags:
      - user
      summary: Get a user by id
      operationId: getUserById
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ResponseUser"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      produces:
      - "*/*"
    parameters:
      - name: userId
        in: path
        description: User id from which will retrieve
        required: true
        type: integer
        format: int64
